name: hello
on: push

jobs:
    job1:
        name: First job
        runs-on: ubuntu-latest
        steps:
            - name: Step one
              run: date
    job2:
        name: Second job
        runs-on: windows-latest
        steps:
            - name: Step one
              run: Get-Date
    job3:
        name: Third job
        needs: [job1, job2]
        runs-on: macos-latest
        steps:
            - name: Step one
              run: date
    job4:
        name: Forth job
        needs: [job1, job2, job3, job4]
        runs-on: ubuntu-latest
        steps: 
            - name: get date
              run: date
